import { Platform, StyleSheet } from "react-native";

const color_list = {
  black: "#000",
  orange: "#e8ab30",
  green: "#49745e",
  green_light: "#49745e35",
  green_dark: "#3a5d4a",
  cream: "#f8f6f1",
  white: "#fff",
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: color_list.cream,
    paddingHorizontal: 20,
  },
  gradient: {
    flex: 1,
  },
  content: {
    flex: 1,
    justifyContent: "space-between",
    paddingHorizontal: 30,
    paddingVertical: 50,
  },
  logoContainer: {
    alignItems: "center",
    marginTop: 40,
  },
  iconCircle: {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: "rgba(255, 255, 255, 0.3)",
  },
  titleContainer: {
    alignItems: "center",
    marginTop: -50,
  },
  title: {
    fontSize: 48,
    fontWeight: "bold",
    color: color_list.white,
    marginBottom: 8,
    letterSpacing: 1,
  },
  subtitle: {
    fontSize: 24,
    color: color_list.white,
    opacity: 0.9,
    marginBottom: 20,
    fontWeight: "300",
    letterSpacing: 2,
    textAlign: "center",
  },
  description: {
    fontSize: 16,
    color: color_list.white,
    textAlign: "center",
    lineHeight: 24,
    opacity: 0.85,
    paddingHorizontal: 10,
  },
  decorativeContainer: {
    position: "absolute",
    width: "100%",
    height: "100%",
    top: 0,
    left: 0,
  },
  circle: {
    position: "absolute",
    borderRadius: 1000,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
  },
  circle1: {
    width: 200,
    height: 200,
    top: -50,
    right: -50,
  },
  circle2: {
    width: 150,
    height: 150,
    bottom: 100,
    left: -30,
  },
  circle3: {
    width: 100,
    height: 100,
    top: "40%",
    right: 20,
  },
  buttonContainer: {
    alignItems: "center",
    marginBottom: 20,
  },
  button: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: color_list.white,
    paddingVertical: Platform.OS === "ios" ? 15 : 10,
    paddingHorizontal: Platform.OS === "ios" ? 40 : 0,
    borderRadius: 30,
    gap: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
    // minWidth: 200,
  },
  buttonText: {
    fontSize: 18,
    fontWeight: "bold",
    color: color_list.green,
    letterSpacing: 0.5,
  },
  buttonStarted: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    paddingHorizontal: 40,
    borderRadius: 30,
    gap: 10,
    minWidth: 200,
  },
  btn_icon: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    backgroundColor: color_list.white,
    justifyContent: "center",
    alignItems: "center",
  },
  shadow: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  footerText: {
    marginTop: 20,
    fontSize: 14,
    color: color_list.white,
    opacity: 0.7,
  },
  h_container: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 15,
  },
  sub_title: { fontSize: 16, color: "gray" },
  new_com_container: {
    borderRadius: 10,
    backgroundColor: color_list.green,
    padding: 20,
    marginBottom: 0,
  },
  new_book_img: {
    width: 120,
    height: 180,
    borderRadius: 8,
  },
  new_book_title: {
    color: color_list.white,
    fontSize: 18,
    fontWeight: "bold",
  },
  new_book_text: {
    color: color_list.white,
    fontSize: 13,
    lineHeight: 16,
  },
  circle_premium: {
    position: "absolute",
    top: -5,
    right: -5,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: color_list.orange,
    justifyContent: "center",
    alignItems: "center",
  },
  sectionHeader: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#111827",
    marginBottom: 4,
  },
  sectionSubtitle: {
    fontSize: 14,
    color: "#6B7280",
  },
  emptyState: {
    padding: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyStateText: {
    fontSize: 16,
    color: "#6B7280",
    textAlign: "center",
  },
  container_book_collections: {
    flex: 1,
    marginTop: 0,
  },
  container_book_collections_title: {
    fontSize: 18,
    fontWeight: "bold",
  },
  book_grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginTop: 10,
    paddingBottom: 20,
  },
  book_card: {
    width: "48%",
    backgroundColor: color_list.white,
    borderRadius: 10,
    marginBottom: 15,
    overflow: "hidden",
  },
  book_card_img: {
    width: "100%",
    height: 200,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    backgroundColor: color_list.green_dark,
  },
  circle_premium_small: {
    position: "absolute",
    top: 5,
    right: 5,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: color_list.orange,
    justifyContent: "center",
    alignItems: "center",
  },
  book_card_title: {
    fontSize: 14,
    fontWeight: "bold",
    color: "black",
    marginBottom: 4,
    minHeight: 34,
  },
  book_card_author: {
    fontSize: 12,
    color: "gray",
    marginBottom: 8,
  },
  book_card_footer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  book_card_rating: {
    fontSize: 12,
    color: "black",
    marginLeft: 4,
    fontWeight: "600",
  },
  book_card_views: {
    fontSize: 12,
    color: "gray",
    marginLeft: 4,
  },
  paginationContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 10,
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: color_list.green_light,
    marginHorizontal: 4,
  },
  paginationDotActive: {
    width: 24,
    backgroundColor: color_list.green,
  },
});

export { color_list, styles };
