import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  section: {
    padding: 20,
  },
  paragraph: {
    fontSize: 15,
    color: "#4B5563",
    lineHeight: 24,
    marginBottom: 8,
  },
  viewExample: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  textNormal: {
    fontSize: 16,
    color: "#111827",
    marginBottom: 8,
  },
  textBold: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#111827",
    marginBottom: 8,
  },
  textItalic: {
    fontSize: 16,
    fontStyle: "italic",
    color: "#111827",
    marginBottom: 8,
  },
  textColored: {
    fontSize: 16,
    color: "#3B82F6",
    marginBottom: 8,
  },
  textLarge: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#111827",
  },
  imageContainer: {
    alignItems: "center",
  },
  imagePlaceholder: {
    width: 200,
    height: 200,
    backgroundColor: "#F3F4F6",
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#E5E7EB",
    borderStyle: "dashed",
  },
  placeholderText: {
    marginTop: 8,
    fontSize: 14,
    color: "#6B7280",
  },
  textInput: {
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: "#FFFFFF",
  },
  inputResult: {
    marginTop: 12,
    fontSize: 14,
    color: "#059669",
    fontWeight: "500",
  },
  buttonContainer: {
    marginTop: 8,
  },
  customButton: {
    flexDirection: "row",
    backgroundColor: "#EC4899",
    padding: 16,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  customButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 8,
  },
  exampleLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#6B7280",
    marginBottom: 8,
  },
  switchContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 12,
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  switchLabel: {
    fontSize: 16,
    color: "#111827",
    fontWeight: "500",
  },
  flexRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  flexColumn: {
    flexDirection: "column",
    alignItems: "center",
    gap: 12,
  },
  styleSheetExample: {
    padding: 10,
    backgroundColor: "#FEF3C7",
    borderRadius: 8,
  },
  styleSheetText: {
    color: "#92400E",
    fontWeight: "600",
  },
  multipleStyleBase: {
    padding: 10,
    borderRadius: 8,
  },
  multipleStyleExtra: {
    backgroundColor: "#DBEAFE",
    borderWidth: 2,
    borderColor: "#3B82F6",
  },
  multipleStyleText: {
    color: "#1E40AF",
    fontWeight: "600",
  },
  shadowBox: {
    padding: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  shadowText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#111827",
    textAlign: "center",
  },
  elevationBox: {
    padding: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    elevation: 5,
  },
  elevationText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#111827",
    textAlign: "center",
  },
  exerciseCard: {
    backgroundColor: "#F9FAFB",
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    borderLeftWidth: 4,
    borderLeftColor: "#3B82F6",
  },
  exerciseHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  exerciseTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#111827",
    marginLeft: 8,
  },
  exerciseDescription: {
    fontSize: 14,
    color: "#6B7280",
    lineHeight: 20,
  },
  tipCard: {
    flexDirection: "row",
    backgroundColor: "#FFFBEB",
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#FDE68A",
  },
  tipIcon: {
    width: 40,
    height: 40,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  tipContent: {
    flex: 1,
  },
  tipTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#92400E",
    marginBottom: 4,
  },
  tipText: {
    fontSize: 14,
    color: "#78350F",
    lineHeight: 20,
  },
  summaryCard: {
    backgroundColor: "#F0FDF4",
    padding: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#BBF7D0",
  },
  summaryText: {
    fontSize: 15,
    color: "#166534",
    lineHeight: 28,
    marginBottom: 8,
  },
  nextStepCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  nextStepIcon: {
    width: 48,
    height: 48,
    backgroundColor: "#F3F4F6",
    borderRadius: 24,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  nextStepContent: {
    flex: 1,
  },
  nextStepTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#111827",
    marginBottom: 4,
  },
  nextStepSubtitle: {
    fontSize: 14,
    color: "#6B7280",
  },
});

export { styles };
